language: node_js
node_js:
  - "node"
python:
  - "2.7"
script: make test-coveralls
cache:
  bundler: true
  pip: true
  directories:
  - node_modules # NPM packages
sudo: false
before_install:
  - pip install --user quandl
# - pip install --user scipy


